/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips/index'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as TripsTripIdRouteImport } from './routes/trips/$tripId'
import { Route as PeopleCreateRouteImport } from './routes/people/create'
import { Route as PeoplePersonIdRouteImport } from './routes/people/$personId'
import { Route as TripsTripIdEditRouteImport } from './routes/trips/$tripId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleCreateRoute = PeopleCreateRouteImport.update({
  id: '/people/create',
  path: '/people/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdEditRoute = TripsTripIdEditRouteImport.update({
  id: '/trips/$tripId_/edit',
  path: '/trips/$tripId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/people/create': typeof PeopleCreateRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/people/': typeof PeopleIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/trips/$tripId/edit': typeof TripsTripIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/people/create': typeof PeopleCreateRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/people': typeof PeopleIndexRoute
  '/trips': typeof TripsIndexRoute
  '/trips/$tripId/edit': typeof TripsTripIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/people/create': typeof PeopleCreateRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/people/': typeof PeopleIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/trips/$tripId_/edit': typeof TripsTripIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/people/$personId'
    | '/people/create'
    | '/trips/$tripId'
    | '/people/'
    | '/trips/'
    | '/trips/$tripId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/people/$personId'
    | '/people/create'
    | '/trips/$tripId'
    | '/people'
    | '/trips'
    | '/trips/$tripId/edit'
  id:
    | '__root__'
    | '/'
    | '/people/$personId'
    | '/people/create'
    | '/trips/$tripId'
    | '/people/'
    | '/trips/'
    | '/trips/$tripId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PeopleCreateRoute: typeof PeopleCreateRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
  TripsTripIdEditRoute: typeof TripsTripIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/create': {
      id: '/people/create'
      path: '/people/create'
      fullPath: '/people/create'
      preLoaderRoute: typeof PeopleCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId_/edit': {
      id: '/trips/$tripId_/edit'
      path: '/trips/$tripId/edit'
      fullPath: '/trips/$tripId/edit'
      preLoaderRoute: typeof TripsTripIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PeopleCreateRoute: PeopleCreateRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
  TripsTripIdEditRoute: TripsTripIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
